import { type ContractData } from 'src/contract/contract-document';

export const SAMPLE_CONTRACT_DATA: ContractData = {
  number: '1012',
  signedOn: '2026-10-09',
  clientName: 'Азизов Бахтиёр',
  clientPhone: '+998901234567',
  address: 'Юнусабадский, 12-кв, д. 5, кв. 18',
  subtotal: 5_100_000,
  discount: 240_000,
  total: 4_860_000,
  prepayment: 2_430_000,
  termDays: 20,
  paintColor: 'чёрный матовый',
  openings: [
    {
      title: 'Проём 1',
      product: 'М-03',
      widthCm: 150,
      heightCm: 180,
      projectionKind: 'BOTTOM',
      projectionCm: 30,
      quantity: 1,
      areaSquareMeters: 3.69,
      visorText: null,
      lineTotal: 1_930_000,
      designId: 'design-m03',
    },
    {
      title: 'Проём 2',
      product: 'М-03',
      widthCm: 120,
      heightCm: 150,
      projectionKind: 'NONE',
      projectionCm: 0,
      quantity: 2,
      areaSquareMeters: 3.6,
      visorText: null,
      lineTotal: 1_170_000,
      designId: 'design-m03',
    },
    {
      title: 'Проём 3',
      product: 'ARM-13',
      widthCm: 140,
      heightCm: 200,
      projectionKind: 'BOTTOM_AND_TOP',
      projectionCm: 15,
      quantity: 1,
      areaSquareMeters: 3.82,
      visorText: 'Козырёк Стандарт, 160 см',
      lineTotal: 2_000_000,
      designId: 'design-arm13',
    },
  ],
};
